### ISSUE TITLE
Issue with OKZoomer beta 6 on fabric 0.14.6+0.14.7

### ISSUE THREAD

**Issue by ghost** [joaoh1/OkZoomer#79] opened 2022-06-10 20:04 UTC
With only API and OKZoomer loaded, not sure what else you need to know, I'll put what I can find easily here;

A mod crashed on startup!
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'quilt_command'!
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:164)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'quilt_command'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:162)
	... 2 more
Caused by: java.lang.ExceptionInInitializerError
	at org.quiltmc.qsl.command.impl.PreLaunchInitializer.onPreLaunch(PreLaunchInitializer.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 4 more
Caused by: java.lang.RuntimeException: Failed to load Classloader fields
	at org.quiltmc.qsl.base.impl.PreLaunchHacks.<clinit>(PreLaunchHacks.java:49)
	... 6 more
Caused by: java.lang.NoSuchMethodException: net.fabricmc.loader.impl.launch.knot.KnotClassLoader.addURL(java.net.URL)
	at java.base/java.lang.Class.getMethod(Class.java:2227)
	at org.quiltmc.qsl.base.impl.PreLaunchHacks.<clinit>(PreLaunchHacks.java:46)
	... 6 more

Sadly I dont know much more, heres my latest.log file as well
[latest.log](https://github.com/EnnuiL/OkZoomer/files/8881971/latest.log)

**Comment by ghost** [comment] 2022-06-10 20:05
forgot to mention that it works fine on fabric 0.14.5

**Comment by EnnuiL** [comment] 2022-06-11 05:02
Duplicate of #74; As noted on the CurseForge page, there's nothing I can do about the issue

**Closed as not planned by EnnuiL** 2022-06-11 05:02 UTC
