### ISSUE TITLE
Crash when going in third person

### ISSUE THREAD

**Issue by jasminexs** [joaoh1/OkZoomer#54] opened 2022-03-06 01:46 UTC
Playing on 1.18.2 with no mods except the most recent version of okzoomer and fabric API, when I try to go into third person the game crashes.
Edit: it's caused by something going wrong when rendering the player, same thing happens when I try to use freelook

**Comment by EnnuiL** [comment] 2022-03-06 02:46
Duplicate of #53; An update of Ok Zoomer for 1.18.2 is on progress and it will release soon

**Closed as completed by EnnuiL** 2022-03-06 02:46 UTC
