### ISSUE TITLE
Unnormal amount of frame drop 

### ISSUE THREAD

**Issue by WhatsCosmicCrackin** [joaoh1/OkZoomer#47] opened 2021-12-17 10:58 UTC
With "ok zoomer" installed I'm getting an average of 65 fps. without I get 76 fps. the test was performed over 2 min of looking at heavy terrain standing still with a command to look at the same block every time, with no other plugins installed only "fabric-api-0.44.0+1.18" and "ok zoomer-5.0.0-beta.3+1.17.1".
I know it's only a 11 fps difference but it's significant, especially because the mod isn't even in use

![2021-12-17_05 46 46](https://user-images.githubusercontent.com/96290981/146534312-16384a5d-892e-4f10-bad3-05f51a1d3cf4.png)

**Comment by EnnuiL** [comment] 2021-12-18 23:03
I've noticed that the "Without Ok Zoomer" comparison omits the Fabric API; Could you try comparing Fabric with Fabric API and Fabric with Fabric API and Ok Zoomer?
Because if my suspicions are correct, it isn't an Ok Zoomer issue, but a Fabric API one, and if it's indeed FAPI, I'd be pretty concerned about it

**Comment by EnnuiL** [comment] 2022-03-13 02:37
Issue #57 confirmed that this isn't a FAPI issue, I'll investigate this issue

**Comment by EnnuiL** [comment] 2022-03-13 20:29
Hmm, I did some comparisons between Ok Zoomer and no Ok Zoomer;
On an instance containing only Fabric API and LazyDFU, I managed to reproduce this slight hit
My main suspect is LibZoomer and its set iterations that is causing those slight slowdowns; Thankfully, on an already-intensive scenarios and with optimization mods (such as an another MC instance but with Canvas), the maximum that it has done is to make the stable FPS be slightly wobbly but otherwise, the FPS rate remained the same

Despite that, a mod that is feature-packed should not mean it should affect the FPS at all, and so, I'm working towards making those set iterations not affect performance at all. I already managed to get some extra FPS from switching to FastUtils! But yeah, I don't intend to stop there

Here are the screenshots so far:

<details>
<summary>Comparison Screenshots</summary>
Ok Zoomer:

![2022-03-13_17 11 35](https://user-images.githubusercontent.com/85590273/158077647-82e553fe-960d-4585-9d5c-413d5efa0813.png)

No Ok Zoomer:

![2022-03-13_17 14 06](https://user-images.githubusercontent.com/85590273/158077659-d2ca0806-42b5-4832-83ec-130a51b69f3a.png)

Ok Zoomer with usage of FastUtils on LibZoomer:

![2022-03-13_17 16 57](https://user-images.githubusercontent.com/85590273/158077801-4785795a-a417-4288-b3bf-b34887edda21.png)

</details>

**Comment by EnnuiL** [comment] 2022-03-25 20:46
And with a change that reduces those iterations when they're not necessary, I managed to reduce the tiny lag introduced by LibZoomer back to 0! Therefore, the next Ok Zoomer update will finally fix this issue

<details>
<summary>Comparison</summary>

![image](https://user-images.githubusercontent.com/85590273/160198348-43af2a58-176e-4153-9bc1-7ef90cdac583.png)
</detail>

**Comment by EnnuiL** [comment] 2022-04-10 03:54
Fixed on LibZoomer 0.4.1, which is now used by Ok Zoomer 5.0.0-beta.6

**Closed as completed by EnnuiL** 2022-04-10 03:54 UTC
Labels: bug
