### ISSUE TITLE
Latest Fabric version (5.0.0-beta.6) crashes on startup

### ISSUE THREAD

**Issue by theRookieCoder** [joaoh1/OkZoomer#75] opened 2022-04-22 13:25 UTC
If I run Fabric Loader 0.14.0 with Fabric API 0.51.1 and OkZoomer 5.0.0-beta.6, the game crashes with the following error:
```log
[18:51:24] [main/ERROR]: A mod crashed on startup!
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'quilt_command'!
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:156) ~[fabric-loader-0.14.0.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:69) [fabric-loader-0.14.0.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.0.jar:?]
Caused by: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'quilt_command'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.0.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.0.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.0.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.0.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:154) ~[fabric-loader-0.14.0.jar:?]
	... 2 more
Caused by: java.lang.ExceptionInInitializerError
	at org.quiltmc.qsl.command.impl.PreLaunchInitializer.onPreLaunch(PreLaunchInitializer.java:33) ~[quilt_command-1.0.0+1.18.2-SNAPSHOT-5739c0c319a3f50b.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.0.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.0.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:154) ~[fabric-loader-0.14.0.jar:?]
	... 2 more
Caused by: java.lang.RuntimeException: Failed to load Classloader fields
	at org.quiltmc.qsl.base.impl.PreLaunchHacks.<clinit>(PreLaunchHacks.java:49) ~[quilt_base-1.0.0+1.18.2-SNAPSHOT-95e80be7208cdff7.jar:?]
	at org.quiltmc.qsl.command.impl.PreLaunchInitializer.onPreLaunch(PreLaunchInitializer.java:33) ~[quilt_command-1.0.0+1.18.2-SNAPSHOT-5739c0c319a3f50b.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.0.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.0.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:154) ~[fabric-loader-0.14.0.jar:?]
	... 2 more
Caused by: java.lang.NoSuchMethodException: net.fabricmc.loader.impl.launch.knot.KnotClassLoader.addURL(java.net.URL)
	at java.lang.Class.getMethod(Class.java:2227) ~[?:?]
	at org.quiltmc.qsl.base.impl.PreLaunchHacks.<clinit>(PreLaunchHacks.java:46) ~[quilt_base-1.0.0+1.18.2-SNAPSHOT-95e80be7208cdff7.jar:?]
	at org.quiltmc.qsl.command.impl.PreLaunchInitializer.onPreLaunch(PreLaunchInitializer.java:33) ~[quilt_command-1.0.0+1.18.2-SNAPSHOT-5739c0c319a3f50b.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.0.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.0.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:154) ~[fabric-loader-0.14.0.jar:?]
	... 2 more
```

**Comment by EnnuiL** [comment] 2022-04-22 14:11
Duplicate of #74

**Closed as completed by EnnuiL** 2022-04-22 14:11 UTC
