### ISSUE TITLE
Minecraft crashes when we try to zoom.

### ISSUE THREAD

**Issue by devendrapoonia** [joaoh1/OkZoomer#39] opened 2021-09-27 14:08 UTC
Whenever I try to press C key and try to zoom, minecraft crashes instantly. C key is bound to any other action.
Please fix this.

Minecraft Version - Fabric 1.17
Launcher - TLauncher

Here is crash report.

---- Minecraft Crash Report ----
// There are four lights!

Time: 27/09/21, 3:25 pm
Description: Unexpected error

java.lang.ClassCastException: class java.lang.Double cannot be cast to class net.minecraft.class_746 (java.lang.Double is in module java.base of loader 'bootstrap'; net.minecraft.class_746 is in unnamed module of loader net.fabricmc.loader.launch.knot.KnotClassLoader @5cde6747)
	at org.spongepowered.asm.synthetic.args.Args$5.set(Args$5.java)
	at net.minecraft.class_312.args$bfl000$modifyLookDirection(class_312.java:1606)
	at net.minecraft.class_312.method_1606(class_312.java:266)
	at net.minecraft.class_310.method_1523(class_310.java:1086)
	at net.minecraft.class_310.method_1514(class_310.java:728)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at org.spongepowered.asm.synthetic.args.Args$5.set(Args$5.java)
	at net.minecraft.class_312.args$bfl000$modifyLookDirection(class_312.java:1606)

-- Affected level --
Details:
	All players: 1 total; [class_746['CuteUtkarsh'/10995, l='ClientLevel', x=630.80, y=67.00, z=-76.01]]
	Chunk stats: 1024, 529
	Level dimension: minecraft:overworld
	Level spawn location: World: (467,69,-1466), Section: (at 3,5,6 in 29,4,-92; chunk contains blocks 464,0,-1472 to 479,255,-1457), Region: (0,-3; contains chunks 0,-96 to 31,-65, blocks 0,0,-1536 to 511,255,-1025)
	Level time: 25048 game time, 138966 day time
	Server brand: Paper
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:370)
	at net.minecraft.class_310.method_1587(class_310.java:2399)
	at net.minecraft.class_310.method_1514(class_310.java:752)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 2256055776 bytes (2151 MiB) / 2717908992 bytes (2592 MiB) up to 5838471168 bytes (5568 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i3-6100U CPU @ 2.30GHz
	Identifier: Intel64 Family 6 Model 78 Stepping 3
	Microarchitecture: Skylake (Client)
	Frequency (GHz): 2.30
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 4
	Graphics card #0 name: Intel(R) HD Graphics 520
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x1916
	Graphics card #0 versionInfo: DriverVersion=21.20.16.4534
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Virtual memory max (MB): 34305.90
	Virtual memory used (MB): 9416.45
	Swap memory total (MB): 26240.00
	Swap memory used (MB): 443.94
	JVM Flags: 10 total; -Xmn128M -Xmx5553M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		baritone: Baritone 1.7.0
		com_velocitypowered_velocity-native: velocity-native 1.1.0-SNAPSHOT
		ctm: ConnectedTexturesMod for Fabric 0.5.1+1.17
		fabric: Fabric API 0.40.1+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b446313
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.3.0+cbda931818
		fabric-biome-api-v1: Fabric Biome API (v1) 3.2.0+cbda931818
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+a02b446318
		fabric-command-api-v1: Fabric Command API (v1) 1.1.3+5ab9934c18
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa18
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+cbda931818
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.3.0+cbda931818
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da31018
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.11+6cefd57718
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.2.3+87cc6e4c18
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.10+fc40aa9d18
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa18
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.7+cbda931818
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+cbda931818
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab612118
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+cbda931818
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3e18
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b446318
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b446318
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa18
		fabric-models-v0: Fabric Models (v0) 0.3.0+a02b446318
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.13+cbda931818
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b446318
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa18
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+cbda931818
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b446318
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b446318
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.10+e2961fee18
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.4+cbda931818
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.8+cbda931818
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.3+4658223018
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b446313
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.14+4658223018
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.4+4658223018
		fabric-rendering-v1: Fabric Rendering (v1) 1.8.2+ffb6d41e18
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.8+a00e834b18
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.4+cbda931818
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+cbda931818
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.13+5ab9934c18
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.1+b06cb95b18
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+a02b446318
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab612118
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.3.1+4658223018
		fabricloader: Fabric Loader 0.11.6
		fatxporbs: Fat Experience Orbs 1.0.1
		fiber: fiber 0.23.0-2
		hydrogen: Hydrogen 0.3
		ias: In-Game Account Switcher 7.1.2
		indium: Indium 1.0.0+mc1.17.1
		java: OpenJDK 64-Bit Server VM 16
		krypton: Krypton 0.1.4
		lambdynlights: LambDynamicLights 2.0.2+1.17
		libzoomer: LibZoomer 0.2.1+1.17
		lithium: Lithium 0.7.4
		meteor-client: Meteor Client 0.4.5
		minecraft: Minecraft 1.17.1
		multiconnect: MultiConnect 1.4.15
		multiconnect-api: MultiConnect API 1.4.15
		okzoomer: Ok Zoomer 5.0.0-beta.2+1.17
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		smoothboot: Smooth Boot 1.16.5-1.6.0
		sodium: Sodium 0.3.2+build.7
		spruceui: SpruceUI 3.2.0+1.17
		starlight: Starlight 1.0.0+fabric.73f6d37
		xaerominimap: Xaero's Minimap 21.16.0
	Launched Version: Fabric 1.17.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Intel(R) HD Graphics 520 GL version 3.2.0 - Build 21.20.16.4534, Intel
	Window size: 1920x1001
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: id=1282, source=API, type=ERROR, severity=HIGH, message='Error has been generated. GL error GL_INVALID_OPERATION in (null): (ID: 173538523) Generic error' x 3815
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i3-6100U CPU @ 2.30GHz

-- Meteor Client --
Version: 0.4.5

[Combat]:
Criticals (criticals)

[Player]:
Anti Hunger (anti-hunger)
No Break Delay (no-break-delay)
Portals (portals)

[Movement]:
Entity Control (entity-control)
Jesus (jesus)
No Fall (no-fall)
Sprint (sprint)

[Render]:
Esp (esp)
Fullbright (fullbright)
HUD (HUD)
Tracers (tracers)
Waypoints (waypoints)

[Misc]:
Anti Packet Kick (anti-packet-kick)

**Comment by devendrapoonia** [comment] 2021-09-27 14:11
Here is crash report file.

[crash-2021-09-27_15.25.40-client.txt](https://github.com/EnnuiL/OkZoomer/files/7236885/crash-2021-09-27_15.25.40-client.txt)

**Comment by EnnuiL** [comment] 2021-09-28 12:28
Duplicate of #28, except not the same mod; According to the bug report, the hack client is the one causing the crash by modifying the code with a non-compatible method (most likely a `@Redirect` mixin), and like #28, I can't do anything on my side

**Closed as completed by EnnuiL** 2021-09-28 12:28 UTC
Labels: bug, external-issue
