### ISSUE TITLE
OK Zoomer for 1.17

### ISSUE THREAD

**Issue by Minionguyjpro** [joaoh1/OkZoomer#26] opened 2021-06-18 15:06 UTC
Make OK Zoomer for 1.17. Because its now released.

**Comment by EnnuiL** [comment] 2021-06-19 19:16
1) Duplicate of #22
2) If you haven't noticed, the second 5.0.0 beta (which is for 1.17) is already work-in-progress; It was only until quite recently that problems that stopped me from working on it like a lack of a non-bloated config screen API and a lack of motivation were solved, and despite that, there's still a final roadblock to come over, and also there's still a lot to do until I can say it's ready; So, have some patience because the next beta will be released when it's done, and I'm already actively working on it

**Closed as completed by EnnuiL** 2021-06-19 19:16 UTC

**Comment by Minionguyjpro** [comment] 2021-06-20 10:59
does the beta also work with the now official 1.17 release?
