### ISSUE TITLE
Crash on Minecraft 1.17

### ISSUE THREAD

**Issue by iwillreku3206** [joaoh1/OkZoomer#24] opened 2021-06-09 16:12 UTC
As the title says, the mod appears to cause a crash on Minecraft 1.17 when joining a world

`[00:04:39] [Render thread/FATAL]: Unreported exception thrown!
java.lang.NoSuchMethodError: 'void com.mojang.blaze3d.systems.RenderSystem.defaultAlphaFunc()'
	at net.minecraft.class_757.handler$zbg000$injectZoomOverlay(class_757.java:1554) ~[intermediary-minecraft-1.17-client.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:854) ~[intermediary-minecraft-1.17-client.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1114) ~[intermediary-minecraft-1.17-client.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:730) [intermediary-minecraft-1.17-client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:217) [intermediary-minecraft-1.17-client.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226) [fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146) [fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.3.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]`

OS: Windows 10 ver 20H2
Launcher: MultiMC version 0.6.12-develop-2085
Fabric Loader Version: 0.11.3
Java Version: OpenJDK 16.0.1 x64
Other Mods Installed:

- Fabric API (version 0.34.9+1.17)
- IMBlockerFabric (1.0.12)
- LambDynamicLights(2.0.0+1.17)
- Lithium (0.7.0)
- Mod Menu (2.0.0-beta.7)
- **Ok Zoomer (5.0.0-beta.1+21w03a)** - latest version on curseforge
- WorldEdit (7.2.6-SNAPSHOT+5811-7d7da2d)

I am guessing that this error is due to the fact that the latest version was written for a 4-5 month old snapshot?

**Comment by ageekdude** [comment] 2021-06-09 19:41
I have the same problem, I have the crash report attached.
[crash-2021-06-09_14.38.57-client.txt](https://github.com/joaoh1/OkZoomer/files/6626471/crash-2021-06-09_14.38.57-client.txt)

**Comment by joaoh1** [comment] 2021-06-09 19:46
Duplicate of #22. Due to few roadblocks, it won't be easy to update it to the full 1.17 update; So, for now, have patience as I try to figure this out

**Closed by joaoh1** 2021-06-09 19:46 UTC
