### ISSUE TITLE
Instant crash on Smooth Multiplier above 1 (1.17)

### ISSUE THREAD

**Issue by Hlebuw3k** [joaoh1/OkZoomer#37] opened 2021-08-29 01:35 UTC
Title. Should not crash the game, but just undo the setting. Crash report:
[crash-2021-08-29_04.14.32-client.txt](https://github.com/EnnuiL/OkZoomer/files/7071752/crash-2021-08-29_04.14.32-client.txt)

**Comment by EnnuiL** [comment] 2021-08-30 11:18
Duplicate of #33; I'll deal with this problem later though

**Closed as completed by EnnuiL** 2021-08-30 11:18 UTC
