### ISSUE TITLE
Can't zoom unless I reset OKZoomer settings

### ISSUE THREAD

**Issue by Kratos-Lee520** [joaoh1/OkZoomer#41] opened 2021-10-27 18:56 UTC
I am on 1.17.1 and I have to reset all my Okzoomer settings to default every time I load up MC because the mod won't work unless I reset it. The only settings I touch are "Reset zoom with mouse" to off, " Print owo on start" to off, and "reduce sensitivity" to on. But the smooth multiplier has this in the box "2.2250738585072014E-308" and the maximum linear step also has the exact same thing in its box. When I reset to default the numbers change to .75 for smooth multiplier and .25 for max linear step, and change the 3 settings I mentioned, then it works fine. So I think it has something to do with these 2 text boxes setting itself to this weird number when I start MC for some reason, but I don't know how to make it stop. I can't even find a config file for the mod, I would've looked there to see if I could find the issue.

**Comment by Kratos-Lee520** [comment] 2021-11-04 02:28
Can confirm changing the settings in the config doesn't completely fix the issue. It'll let me zoom in, but I can't scroll unless I go to the mod menu config for OKzoomer and reset the settings, then the scroll works again.

**Comment by tomhula** [comment] 2021-11-17 19:27
Same problem.

**Comment by EnnuiL** [comment] 2021-11-18 01:21
Huh, this is a really weird issue; I have no idea why that could happen (and I couldn't reproduce it on my PC), although I'm sure that it isn't the config screen's fault
I have rewritten the config system, so perhaps it should be fixed on the next update? We'll see

**Comment by tomhula** [comment] 2021-11-18 05:41
Also, the config screen has two reset buttons for some reason. And only the upper one makes you able to use the zoom again and with each Minecraft re-open, it's broken again.

**Comment by tomhula** [comment] 2021-11-18 05:42
So the default config, from when you install the mod could be wrong? And when you use the reset button, the changes won't save to the file?

**Comment by EnnuiL** [comment] 2021-11-18 11:34
> Also, the config screen has two reset buttons for some reason. And only the upper one makes you able to use the zoom again and with each Minecraft re-open, it's broken again.

The Reset button on the "Presets" section is the one which resets your settings to the chosen preset; The one in the bottom  discards your changes (therefore, resetting the settings to the ones you have loaded);
I'll rename the latter to "Discard Changes" in order to prevent confusion

**Comment by tomhula** [comment] 2021-11-18 11:44
Well if you can't find the file it could mean it is not saving. That looks like the issue.

**Comment by Kratos-Lee520** [comment] 2021-11-18 22:15
I actually found the file, figured out what I needed to change, closed MC, changed and saved the config, and 2 of the values still reset themselves. I was able to zoom but not scroll while zoomed. Then after a few days of opening MC, it stopped working and now have to click reset every time again.

**Comment by tomhula** [comment] 2021-12-11 18:20
The latest release is free of this bug, thank you, you can close the issue :)

**Comment by EnnuiL** [comment] 2021-12-11 18:37
Awesome!

**Closed as completed by EnnuiL** 2021-12-11 18:37 UTC
Labels: bug
