### ISSUE TITLE
Adding a Forge Version

### ISSUE THREAD

**Issue by FitiveGaming** [joaoh1/OkZoomer#60] opened 2022-03-15 08:44 UTC
The mod is simply amazing, though it would be even more amazing if the mod is added as a Forge mod as well! Fabric currently has very less mods, those which are compatible need to have at least another **supplement mod** to work...

**Comment by EnnuiL** [comment] 2022-03-15 14:40
Duplicate of #29

**Closed as completed by EnnuiL** 2022-03-15 14:40 UTC
