### ISSUE TITLE
Spyglass overlay dark area is much bigger in third person than in first person

### ISSUE THREAD

**Issue by Disketaa** [joaoh1/OkZoomer#113] opened 2024-10-03 23:29 UTC
![image](https://github.com/user-attachments/assets/1cd2d7b5-d083-4a19-9296-257a08c12536)
![image](https://github.com/user-attachments/assets/23970a3e-5369-4a9a-bcfa-edfc6e8a08d0)

**Comment by EnnuiL** [comment] 2024-10-05 15:34
Ok so, this is a weird one;
For spyglass parity? The zoom still being active outside of first-person perspective is an oversight, but since being able to zoom into your face *is* often a desirable thing, I might work on a Tweaks toggle of some sorts later;
Now for the issue itself? I can't reproduce it with only Ok Zoomer and Fabric API installed, and mods like Sodium and Iris don't appear to affect it; Also to make sure weird shenanigans weren't involved, I tested on Sintyra Connector despite the broken mouse sensitivity, and there was no broken spyglass overlay;
So yeah, I'm confused; Maybe it's a mod conflict thing?

**Comment by EnnuiL** [comment] 2024-10-05 15:34
oh whoops, accidentally closed this

**Comment by EnnuiL** [comment] 2024-10-14 22:55
OH I see what you mean; This was a failed attempt on parity with Vanilla that will be fixed on the next feature update of Ok Zoomer, stay tuned for more

**Comment by EnnuiL** [comment] 2024-10-15 02:35
Fixed on Ok Zoomer 10.0.0-beta.1

**Closed as completed by EnnuiL** 2024-10-15 02:35 UTC
